services:
  api:
    build: flask
    ports:
      - "8000:5000"
    volumes:
      - ./flask:/app
    env_file: flask/.env
  worker:
    build: worker
    volumes:
      - ./worker:/app
    env_file: worker/.env
  fe:
    image: skimmer-fe
    build: react
    volumes:
      - ./react/src:/app/src
      - ./react/public:/app/public
      - ./react/tailwind.config.js:/app/tailwind.config.js
    ports:
      - "8080:3000"
    env_file: react/.env
  tf:
    image: skimmer-tf
    build: tf
    volumes:
      - ./tf:/app
  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: skimmer
      POSTGRES_USER: skimmer
      POSTGRES_DB: skimmer
    volumes:
      - ./pgdata-16.1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  memcached:
    image: memcached:1.6.22-alpine
    command: ["-m", "4096"]
    ports:
       - "11211:11211"
  rmq:
    image:
        rabbitmq:3.12.10-alpine
    ports:
        - "5672:5672"
