FROM skimmer-fe as skimmer-fe-build
WORKDIR /app
COPY react/src /app/src
COPY react/public /app/public
COPY react/tailwind.config.js /app/tailwind.config.js
RUN REACT_APP_SKIMMER_API_URL=/api GENERATE_SOURCEMAP=false yarn build

FROM nginx:1.25.3-alpine-slim
COPY react/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY react/nginx/cert.pem /etc/nginx/cert.pem
COPY react/nginx/key.pem /etc/nginx/key.pem
COPY --from=skimmer-fe-build /app/build /usr/share/nginx/html
