---
  - name: storage server
    hosts: 127.0.0.1
    connection: local

    tasks:
      - name: install postgres
        apt:
          name: postgresql-16
          state: present

      - name: Make sure pg is started
        ansible.builtin.systemd_service:
          state: started
          name: postgresql

      - name: create db
        become: true
        become_user: postgres
        community.postgresql.postgresql_db:
          name: "{{ db_user }}"

      - name: setup db auth
        become: true
        become_user: postgres
        community.postgresql.postgresql_user:
          db: "{{ db_name }}"
          name: "{{ db_user }}"
          password: "{{ db_password }}"

      - name: grant to public schema
        become: true
        become_user: postgres
        community.postgresql.postgresql_privs:
          db: "{{ db_name }}"
          privs: ALL
          type: schema
          objs: public
          roles: "{{ db_user }}"

      - name: Setup pg to work on network
        postgresql_pg_hba:
          dest: /etc/postgresql/16/main/pg_hba.conf
          contype: host
          users: all
          source: 192.168.1.1/16
          databases: all
          method: scram-sha-256

      - name: Make sure pg is started
        ansible.builtin.systemd_service:
          state: restarted
          name: postgresql
