import os

get = os.environ.get


class Config:
    RABBITMQ_URI = get("RABBITMQ_URI")

    class Flask:
        FLASK_ENDPOINT_UPDATE_CHANNEL = get("FLASK_ENDPOINT_UPDATE_CHANNEL")
        FLASK_ENDPOINT_ACK_MESSAGE = get("FLASK_ENDPOINT_ACK_MESSAGE")
        FLASK_ENDPOINT_VACUUM_MESSAGES = get("FLASK_ENDPOINT_VACUUM_MESSAGES")
        FLASK_ENDPOINT_GET_CHANNELS = get("FLASK_ENDPOINT_GET_CHANNELS")
        FLASK_SECRET_KEY = get("FLASK_SECRET_KEY")
